substitutions:
   name: replace_me

esphome:
  name: ${name}
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: true

<<: !include  ../common.yaml

uart:
  baud_rate: 115200
  tx_pin: GPIO1
  rx_pin: GPIO3

switch:
  - platform: restart
    name: "Restart"
  - platform: template
    name: 'pump'
    id: pump
    turn_on_action:
      - uart.write: [0xA0, 0x01, 0x01, 0xA2]
    turn_off_action:
      - uart.write: [0xA0, 0x01, 0x00, 0xA1]
    optimistic: true
  - platform: template
    name: 'hose1'
    id: hose1
    turn_on_action:
      - uart.write: [0xA0, 0x02, 0x01, 0xA3]
    turn_off_action:
      - uart.write: [0xA0, 0x02, 0x00, 0xA2]
    optimistic: true
  - platform: template
    name: 'hose2'
    id: hose2
    turn_on_action:
      - uart.write: [0xA0, 0x03, 0x01, 0xA4]
    turn_off_action:
      - uart.write: [0xA0, 0x03, 0x00, 0xA3]
    optimistic: true
  - platform: template
    name: 'hose3'
    id: hose3
    turn_on_action:
      - uart.write: [0xA0, 0x04, 0x01, 0xA5]
    turn_off_action:
      - uart.write: [0xA0, 0x04, 0x00, 0xA4]
    optimistic: true
  - platform: template
    name: 'Schedule 6>=schedule<18'
    id: schedule
    optimistic: true
    restore_state: true
    assumed_state: true
    turn_on_action:
    - script.execute: schedule_tick
    turn_off_action:
    - script.execute: schedule_tick

interval:
  - interval: 1s
    then:
      - script.execute: schedule_tick
script:
  - id: schedule_tick
    then:
      - lambda: ''
