esphome:
  name: fridge
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "fridge Fallback Hotspot"

captive_portal:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Toggle"
    on_press:
      - switch.toggle: cooler

switch:
  - platform: gpio
    name: cooler
    pin: GPIO12
    id: cooler

# Example configuration entry
sensor:
  - platform: dht
    pin: 14
    model: SI7021
    temperature:
      id: temperature
      name: "temperature"
    humidity:
      name: "humidity"
    update_interval: 1s
# logging
debug:

logger:
  level: DEBUG
web_server:
  port: 80
  prometheus: true
climate:
  - platform: bang_bang
    sensor: temperature
    name: fridge
    id: fridge
    visual:
      min_temperature: 3.2 째C
      max_temperature: 5.3 째C
    default_target_temperature_low: 3.2 째C
    default_target_temperature_high: 3.4 째C
    cool_action:
      - switch.turn_on: cooler
    idle_action:
      - switch.turn_off: cooler
    heat_action:
      - switch.turn_off: cooler

