# ITEMS IN BOLD NEED EDITING 
substitutions:
   name: cat_camera
 
esphome:
   name: ${name}
   platform: ESP32
   board: esp32dev


<<: !include  ../common.yaml

# feed max31855
spi:
  miso_pin: GPIO15
  clk_pin: GPIO4

sensor:
  - platform: max31855
    name: temperature
    id: temperature
    cs_pin: GPIO2
    update_interval: 1s
    on_value:
      then:
      - if:
          condition:
            sensor.in_range:
              id: temperature
              above: 107
          then:
            - switch.turn_off: heater
          else:
            - switch.turn_on: heater
      - if:
          condition:
            sensor.in_range:
              id: temperature
              above: 97
          then:
            - if:
                condition:
                  switch.is_on: automatic_vent
                then:
                - switch.turn_off: vent
          else:
            - if:
                condition:
                  switch.is_on: automatic_vent
                then:
                - switch.turn_on: vent
            # - switch.turn_on: heater

# enable http
http_request:
  useragent: esphome/sousvide
  timeout: 10s

switch:
  # - platform: gpio
  #   pin: 13
  #   name: "pin13"
  - platform: gpio
    pin: 12
    name: "heater hhh"
    id: heater
    inverted: true
  - platform: template
    name: 'Smoker Vent(ON=open)'
    id: vent
    turn_on_action:
      - http_request.post:
          url: http://smoker/switch/ventonopen/turn_on
    turn_off_action:
      - http_request.post:
          url: http://smoker/switch/ventonopen/turn_off
    optimistic: true
  - platform: template
    name: 'Automatic Smoker Vent Mode(ON=automatic)'
    id: automatic_vent
    optimistic: true
    restore_state: true
