# Config from https://community.home-assistant.io/t/4-channel-relay-esp8266-wifi-board-working-with-esphome/120594/48
# curl -X POST http://gate/switch/relay1/turn_off
esphome:
  name: s31powerplug
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "s31powerplug Fallback Hotspot"

captive_portal:

# Enable Home Assistant API
api:

logger:
  # disable logging to serial port
  baud_rate: 0
  level: DEBUG

ota:
web_server:
  port: 80

uart:
  rx_pin: RX
  baud_rate: 4800

sensor:
  - platform: cse7766
    update_interval: 1s
    current:
      name: "Current"
    voltage:
      name: "Voltage"
    power:
      name: "Power"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff 2 Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Sonoff 2 Relay"
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_ON

status_led:
  pin:
    number: GPIO13

prometheus: