# TODO:
# * create virual switches: UP and DOWN
# * these would use a lambda to increase/decrease a global var
# * that var would then be used in on_value
# * add a virtual sensor to show the global value
# * inject some html to control it
substitutions:
   name: cat_camera

esphome:
  name: $name
  platform: esp32
  board: nodemcu-32s

<<: !include  ../common.yaml

esp32_ble_tracker:

sensor:
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:DB:BC:AA"
    temperature:
      name: "shed-temperature"
    humidity:
      name: "shed-humidity"
    battery_level:
      name: "shed-battery"
  - platform: atc_mithermometer
    mac_address: 'A4:C1:38:AC:BB:EF'
    temperature:
      name: "compost-right-temperature"
    humidity:
      name: "compost-right-humidity"
    battery_level:
      name: "compost-right-battery"
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:49:34:18"
    temperature:
      name: "compost-left-temperature"
    humidity:
      name: "compost-left-humidity"
    battery_level:
      name: "compost-left-battery"
  - platform: atc_mithermometer
    mac_address: A4:C1:38:D1:BE:A0
    temperature:
      name: "compost-legacy-temperature"
    humidity:
      name: "compost-legacy-humidity"
    battery_level:
      name: "compost-legacy-battery"
switch:
  - platform: restart
    name: "Restart"