# TODO:
# * create virual switches: UP and DOWN
# * these would use a lambda to increase/decrease a global var
# * that var would then be used in on_value
# * add a virtual sensor to show the global value
# * inject some html to control it 

esphome:
  name: sousvide
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sousvide Fallback Hotspot"

captive_portal:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Toggle"
    on_press:
      - switch.toggle: heater

switch:
  - platform: gpio
    name: heater
    pin: GPIO12
    id: heater

# temp sensor
dallas:
  - pin: 14
    update_interval: 10s
# Individual sensors
sensor:
  - platform: dallas
    index: 0
    name: temperature
    id: temperature
    # update_interval: 60s
    # in a trigger:
    on_value:
      if:
        condition:
          sensor.in_range:
            id: temperature
            above: 58.0
        then:
          - switch.turn_off: heater
        else:
          - switch.turn_off: heater
          # - switch.turn_on: heater
# logging
debug:
logger:
  level: DEBUG
web_server:
  port: 80
  prometheus: true

