esphome:
  name: sousvide
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sousvide Fallback Hotspot"

captive_portal:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Toggle"
    on_press:
      - switch.toggle: heater

switch:
  - platform: gpio
    name: heater
    pin: GPIO12
    id: heater

# temp sensor
dallas:
  - pin: 14
    update_interval: 1s
# Individual sensors
sensor:
  - platform: dallas
    index: 0
    name: temperature
    id: temperature
# logging
debug:

logger:
  level: DEBUG
web_server:
  port: 80
climate:
  - platform: bang_bang
    sensor: temperature
    name: sousvide
    visual:
      min_temperature: 18 °C
      max_temperature: 100 °C
      temperature_step: 0.1 °C
    default_target_temperature_low: 49 °C
    default_target_temperature_high: 50 °C
    heat_action:
      - switch.turn_on: heater
    idle_action:
      - switch.turn_off: heater

