esphome:
  name: poolpump
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "pool Fallback Hotspot"

captive_portal:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Toggle"
    on_press:
      - switch.toggle: pump

switch:
  - platform: gpio
    name: pump
    pin: GPIO12
    id: pump

# Example configuration entry
sensor:
  - platform: dht
    pin: 14
    model: SI7021
    temperature:
      id: temperature
      name: "temperature"
    humidity:
      name: "humidity"
    update_interval: 1s
# logging
debug:

logger:
  level: DEBUG

web_server:
  port: 80
  prometheus: true

# Example configuration entry
time:
  - platform: sntp
    id: sntp_time
    timezone: America/Los_Angeles
    # start around 7, stop around 4
    on_time:
      - hours: 7
        then:
          - switch.turn_on: pump
      - hours: 16
        then:
          - switch.turn_off: pump

