esphome:
  name: poolpump
  platform: ESP8266
  board: esp8285
  # on_boot:
  #   - switch.turn_on: pump

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "pool Fallback Hotspot"

captive_portal:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Toggle"
    on_press:
      - switch.toggle: pump

switch:
  - platform: gpio
    name: pump
    pin: GPIO12
    id: pump

# Example configuration entry
sensor:
  - platform: dht
    pin: 14
    model: SI7021
    temperature:
      id: temperature
      name: "temperature"
    humidity:
      name: "humidity"
      id: humidity
    update_interval: 10s
# logging
# debug:

logger:
 level: DEBUG

web_server:
  port: 80
prometheus:

# Example configuration entry
time:
  - platform: sntp
    id: sntp_time
    timezone: America/Los_Angeles
    on_time:
    #run pool extra hours if raining or hot
      - hours: 6-9
        then:
          if:
            condition:
              or:
                - sensor.in_range:
                    id: temperature
                    above: 20.0
            then:
              - switch.turn_on: pump
            else:
              - switch.turn_off: pump
      - hours: 9-15
        then:
          - switch.turn_on: pump
      - hours: 21-22
        then:
          if:
            condition:
              or:
                - sensor.in_range:
                    id: temperature
                    above: 20.0
            then:
            - switch.turn_on: pump
      - hours: 16,23,0-5
        then:
          - switch.turn_off: pump
      

