esphome:
  name: poolpump
  platform: ESP8266
  board: esp8285
  # on_boot:
  #   - switch.turn_on: pump

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "pool Fallback Hotspot"

captive_portal:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Physical On/Off"
    on_press:
      - switch.toggle: pump

switch:
  - platform: gpio
    name: pump
    pin: GPIO12
    id: pump
  - platform: template
    name: 'Schedule'
    id: schedule
    optimistic: true
    restore_state: true

sensor:
  - platform: dht
    pin: 14
    model: SI7021
    temperature:
      id: temperature
      name: "temperature"
    humidity:
      name: "humidity"
      id: humidity
    update_interval: 10s
# logging
# debug:

logger:
 level: DEBUG

web_server:
  port: 80
prometheus:

# Example configuration entry
time:
  - platform: sntp
    id: sntp_time
    timezone: America/Los_Angeles

# Example configuration entry
interval:
  - interval: 1min
    then:
      if:
        condition:
          and:
          - switch.is_on: schedule
        then:
          if:
            condition:
            - lambda: |-
                auto time = id(sntp_time).now();
                return (id(temperature).state > 20 && ((time.hour >= 6 && time.hour < 10) || (time.hour >= 21 && time.hour <= 23))) ||
                (time.hour >= 10 && time.hour < 16)
                ;
            then:
            - switch.turn_on: pump
            else:
            - switch.turn_off: pump
