substitutions:
  name: commandline_flag

esphome:
  name: $name
  platform: ESP8266
  board: esp8285

<<: !include  ../common.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Physical On/Off"
    on_press:
      - switch.toggle: pump

switch:
  - platform: gpio
    name: pump
    pin: GPIO12
    id: pump
  - platform: template
    name: 'Schedule'
    id: schedule
    optimistic: true
    restore_state: true
    assumed_state: true

sensor:
  - platform: dht
    pin: 14
    model: SI7021
    temperature:
      id: temperature
      name: "temperature"
    humidity:
      name: "humidity"
      id: humidity
    update_interval: 10s

# Example configuration entry
interval:
  - interval: 1min
    then:
      if:
        condition:
          and:
          - switch.is_on: schedule
        then:
          if:
            condition:
            - lambda: |-
                auto time = id(sntp_time).now();
                return (id(temperature).state > 19 && ((time.hour >= 6 && time.hour < 10) || (time.hour >= 21 && time.hour <= 23))) ||
                (time.hour >= 10 && time.hour < 16)
                ;
            then:
            - switch.turn_on: pump
            else:
            - switch.turn_off: pump
