# Add a pulse mode to run for 60min(during schedule)
# add prometheus alert to trigger it if <8hours in past week
substitutions:
  name: commandline_flag

esphome:
  name: $name
  platform: ESP8266
  board: esp8285
  esp8266_restore_from_flash: true

globals:
   - id: run_timeout
     type: time_t
     restore_value: yes
     initial_value: '0'

<<: !include  ../common.yaml

switch:
  - platform: gpio
    name: pump
    pin: GPIO12
    id: pump
  - platform: template
    name: 'Schedule'
    id: schedule
    optimistic: true
    restore_state: true
    assumed_state: true
    turn_off_action:
    - switch.turn_off: pump
  - platform: template
    name: 'Run for 60min'
    id: toggle_run_timeout
    turn_on_action:
    - script.execute: bump_run_timeout
    turn_off_action:
    - script.execute: bump_run_timeout
    lambda: |-
      auto time = id(sntp_time).now();
      auto timestamp = time.timestamp;
      bool pump_on_from_timeout = timestamp < id(run_timeout);
      return pump_on_from_timeout;
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Physical On/Off"
    on_press:
      - switch.toggle: pump

text_sensor:
  - platform: template
    name: "Run Until"
    id: run_timeout_sensor

sensor:
  - platform: dht
    pin: 14
    model: SI7021
    temperature:
      id: temperature
      name: "temperature"
    humidity:
      name: "humidity"
      id: humidity
    update_interval: 10s

script:
  - id: bump_run_timeout
    then:
      - lambda: |-
          time_t t = id(sntp_time).now().timestamp + 60 * 60;
          id(run_timeout) = t;
          id(schedule_tick).execute();
  - id: update_run_timeout_sensor
    then:
      - lambda: |-
          id(run_timeout_sensor).publish_state(ctime(&id(run_timeout)));
  - id: schedule_tick
    then:
      - lambda: |-
          auto time = id(sntp_time).now();
          auto timestamp = time.timestamp;
          bool pump_on = id(pump).state;
          bool isRunWindow = (time.hour >= 6 && time.hour < 16) || (time.hour >= 21 && time.hour <= 23);
          if (id(schedule).state) {
            bool pump_on_from_timeout = timestamp < id(run_timeout);
            if (pump_on_from_timeout) {
              id(update_run_timeout_sensor).execute();
            } else if (id(temperature).state > 20) {
              id(bump_run_timeout).execute();
              return;
            }
            bool run_pump = pump_on_from_timeout && isRunWindow;
            if (id(pump).state != run_pump) {
              id(pump).toggle();
            }
          }
interval:
  - interval: 1s
    then:
    - script.execute: schedule_tick
